### PR TITLE
Ignore missing .msf files

### PR DESCRIPTION
**Pull request by Abestanis**
This was requested in #171.
The drawback here is that the user is not notified about this.

### CODE REVIEW

**Comment by gyunaev** [comment]
I would keep the original code, but add the QFile::exist check in front of them. The monitoring might not be added because of file watcher-related issues, and user should know about this.

**Comment by Abestanis** [comment]
I will do that for now.

I also had the idea of combining this with the system tray icon tooltip idea from #163.
Instead of all these errors being errors, they would be warnings and they could be for individual mail folders (mork files). We could display a small orange `!` in the icon and display the warning message in the tooltip of the system tray icon. What do you think?

**Comment by Abestanis** [comment]
Something like this:
BirdtrayWarningIdea

**Comment by gyunaev** [comment]
> I also had the idea of combining this with the system tray icon tooltip idea from #163.
> Instead of all these errors being errors, they would be warnings and they could be for individual mail folders (mork files). We could display a small orange `!` in the icon and display the warning message in the tooltip of the system tray icon. What do you think?

I wonder if system tray icon tooltips are supported on all platforms (i.e. Mac)?

**Comment by Abestanis** [comment]
I can test that on Ubuntu and Windows. Since we don't support Mac at the moment, I wouldn't worry about it. Do you like the idea in general?

**Comment by gyunaev** [comment]
> I can test that on Ubuntu and Windows. Since we don't support Mac at the moment, I wouldn't worry about it. Do you like the idea in general?

Yes, its a good idea. I assume that we still print the error in console in this case (especially with -d mode)?

**Comment by Abestanis** [comment]
Awesome, then I will give it a go.

> I assume that we still print the error in console

Yes

**Comment by gyunaev** [comment]
It's ready to be pulled in, right?

**Comment by Abestanis** [comment]
Yes, thanks 👍

**Pull request merged**
