### PR TITLE
Finish the Portuguese and Russian translation

### PR DESCRIPTION
**Pull request by Abestanis**
@igorruckert I did the required changes for you. Closes #328, closes #330, closes #329, closes #327 and closes #323.

### CODE REVIEW

**Comment by gyunaev** [comment]
Please merge the translations yourselves, I´m not reviewing them (except Russian which I can read)

**Comment by Abestanis** [comment]
Yeah, that was the plan. I was kind of surprised when you merged these pull request, especially because I requested some changes in #320.

**Comment by gyunaev** [comment]
Feel free to unpull them :)

**Comment by Abestanis** [comment]
Not necessary, I included the requested changes here.

Let's wait with the release of `1.8.1` until tomorrow, I would like to get the fix for #319 and #321 in.
It is too late for me now, but I should have them ready and tested tomorrow.

**Pull request merged**
