### PR TITLE
Use monospace font for log window

### PR DESCRIPTION
**Pull request by dvalter**
It may improve log readability

### CODE REVIEW

**Comment by Abestanis** [comment]
I like the idea, but doing it like this also changes the font of the `Close` button. If you add the following line to the constructor of the `DialogLogOutput` class instead, we can avoid that:
```c++
logViewer->setFont(QFontDatabase::systemFont(QFontDatabase::FixedFont));
```

**Comment by dvalter** [comment]
Thank you, that's 100% a better solution. I've overlooked both "Close" button font and the reason why Monospace looked better than `QFontDatabase::FixedFont` (it was on my side).

**Comment by gyunaev** [comment]
You can just change the Font property of text editor window in the UI editor. No need to write code at all.

**Comment by Abestanis** [comment]
> You can just change the Font property of text editor window in the UI editor.

I tried that and couldn't get it to work. I was only able to set the font family to one of the fonts I had installed on my system.

**Comment by gyunaev** [comment]
If you set it to a monospace font, and it didn't find the exact one, it should fall back into another monospace font.

**Comment by Abestanis** [comment]
That is not what happened for me. It fell back to the default font, which is obviously not a monospace font.

**Comment by gyunaev** [comment]
Strange, it does so on Linux.

**Pull request merged**
