### PR TITLE
Elaborate confugration file location in README

### PR DESCRIPTION
**Pull request by Chadsr**
This PR simply elaborates in the README as to where the Birdtray configuration file is saved, to avoid confusion since the naming is unexpected.

### CODE REVIEW

**Comment by Abestanis** [comment]
Thank you for your contribution. Could you please clarify, that this is the default path for Linux? On Windows, it's in the registry at `HKEY_CURRENT_USER\Software\ulduzsoft\birdtray`. @ThanosApostolou  Is the config path the same if Birdtray is installed via Flatpak?

**Comment by ThanosApostolou** [comment]
When installed as flatpak, the configuration is at `$HOME/.var/app/com.ulduzsoft.Birdtray/config/ulduzsoft/birdtray.conf`

**Comment by Chadsr** [comment]
I have added Flatpak and Windows locations to the PR. Let me know what you think.

**Comment by Abestanis** [comment]
Looks good to me. 👍

**Pull request merged**
