### PR TITLE
Update Russian translation and fix typos

### PR DESCRIPTION
**Pull request by OlesyaGerasimenko**

### CODE REVIEW

**Comment by Abestanis** [comment]
Thank you for your contribution, looks good from my side.  Thank you as well for becoming a maintainer, we might contact you before we make a new release in case there is any new translations.

I am not a native Russian speaker, so @KOV70 could you please also look over these changes?

**Review by AsriFox — APPROVED** [review]
I'm a native Russian speaker. These changes are good and correct.

**Comment by KOV70** [comment]
Sorry, I was very busy. But I see that everything has already been resolved. Thanks everyone)

**Comment by Abestanis** [comment]
Awesome, thank you very much for the review @AsriFox and @KOV70.

**Comment by Abestanis** [comment]
And of course thank you again @OlesyaGerasimenko for the translations.

**Pull request merged**
